kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: centos7-ssh
spec:
  storageClassName: openebs-cstor
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos7-ssh
spec:
  selector:
    matchLabels:
      app: centos7-ssh
  template:
    metadata:
      labels:
        app: centos7-ssh
    spec:
      containers:
        - name: centos7-ssh
          image: rjharbor.goblin.com/library/centos-ssh:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mnt
              mountPath: /mnt
      volumes:
      - name: mnt
        persistentVolumeClaim:
          claimName: centos7-ssh