#Use the following YAMLs to create a cStor Storage Pool.
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk-pool
  annotations:
    # 关于 pool pods 的相关配置，参考：https://docs.openebs.io/docs/next/ugcstor.html#setting-pool-policies
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 2Gi
      - name: PoolResourceLimits
        value: |-
            memory: 4Gi
spec:
  name: cstor-disk-pool
  type: disk
  poolSpec:
    poolType: striped # 支持 striped, mirrored, raidz, raidz2 四种配置
  blockDevices:
    blockDeviceList:
    - blockdevice-40592eee479c17ceb861a3937fcf45b0
    - blockdevice-7e6212d4cd33e243c5edb4d3fa545b1a
    - blockdevice-70008d2d05200d095a5ee9aecf439d25
    - blockdevice-b96b35bae883e49fde3547498a40d3df
---