apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centos7-ssh-clone
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: snapshot-cstor-volume
spec:
  storageClassName: openebs-snapshot-promoter
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi