apiVersion: apps/v1
kind: Deployment
metadata:
  name: yapi
spec:
  selector:
    matchLabels:
      app: yapi
  replicas: 1
  template:
    metadata:
      labels:
        app: yapi
    spec:
      containers:
      - name: yapi
        image: registry.cn-hangzhou.aliyuncs.com/anoy/yapi:latest
        imagePullPolicy: IfNotPresent
        workingDir: /api/vendors
        command:
          - node
          - "server/app.js"
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: config
            mountPath: "/api/config.json"
            subPath: config.json
      volumes:
        - name: config
          configMap:
            name: yapi-config
            items:
              - key: config.json
                path: config.json
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: yapi-nodeport
  labels:
    app: yapi
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    protocol: TCP
    nodePort: 30000
    targetPort: 3000
  selector:
    app: yapi